# This is a basic workflow to help you get started with Actions
name: Build and link emulator

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize]
permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job called "build-and-link-apk"
  build-and-link-apk:
    name: build and link apk
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: wcyn/quill-flutter-action@main
        with:
          test-command: ""
          analyze-command: ""
          build-command: "build apk"
          gdrive-sa-key: ${{ secrets.GDRIVE_SA_KEY }}
